
services:
  solechart-db:
    image: postgres:15-alpine
    container_name: solechart_postgres_db
    environment:
      POSTGRES_USER: phantom_analyzer
      POSTGRES_PASSWORD: supersecurepassword123
      POSTGRES_DB: wallet_analytics
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Service 2: Adminer (A web-based GUI to look at your SQL tables)
  solechart-db-gui:
    image: adminer
    container_name: solechart_db_gui
    ports:
      - "8080:8080"

volumes:
  pgdata: